# Vector operations


In [2]:
import numpy as np

In [78]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

# addition 
u + v

# subtraction 
u - v

# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

In [79]:
# addition 
u + v

array([ 5, 11, 13, 12])

In [80]:
# subtraction 
u - v

array([-1,  3, -3,  0])

In [81]:
# scalar multiplication 
u * v

array([ 6, 28, 40, 36])

# Multiplication

In [82]:
v.shape[0]

4

In [83]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [84]:
vector_vector_multiplication(u, v)

np.float64(110.0)

In [85]:
v.dot(u)

np.int64(110)

# Matrix-vector multiplication

In [86]:
U = np.array ([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])

In [87]:
U.shape

(3, 4)

In [88]:
import numpy as np

def matrix_vector_multiplication(U, v):
    # Check dimensions match: columns of U == size of v
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        # Proper dot product of row i with vector v
        result[i] = vector_vector_multiplication(U[i], v)

    return result


In [89]:
matrix_vector_multiplication(U,v)

array([98., 31., 35.])

In [90]:
U.dot(v)

array([98, 31, 35])

# Matrix-matrix multiplication


In [93]:
V = np.array ([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])

In [94]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [95]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [96]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity matrix


In [97]:
I = np.eye(3)

In [98]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [100]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)

In [101]:
inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])