In [1]:
import numpy as np

# creating arrays

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

# Converting Lists to Arrays

In [11]:
my_list = [2, 3, 4]
array_from_list = np.array(my_list)

In [12]:
array_from_list

array([2, 3, 4])

# Generating Ranges of Numbers


In [13]:
range_array = np.arange(10) 
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Creating Arrays with Linear Spacing


In [14]:
linspace_array = np.linspace(0, 1, 11)  
linspace_array

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dimensional Arrays

In [21]:
zeros_matrix = np.zeros((5, 2))
ones_matrix = np.ones((5, 2))
constant_matrix = np.full((5, 2), 3)

In [22]:
constant_matrix

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

# Indexing and Slicing Arrays
Like Python lists, you can access elements in Numpy arrays using indexing and slicing. For two-dimensional arrays:


In [35]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[:, 0]  # Gets the first column

In [29]:
first_row

array([4, 5, 6])

In [36]:
first_col

array([2, 4])

# Generating Random Arrays
Numpy can create arrays filled with random numbers. To ensure reproducibility, you can set a seed using np.random.seed():



In [47]:
np.random.seed(3)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1

In [48]:
random_array

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761],
       [0.89294695, 0.89629309],
       [0.12558531, 0.20724288],
       [0.0514672 , 0.44080984]])

# Array Operations
Element-wise Operations

In [54]:
arr = arr + 1   
arr = arr * 2 
arr

382

# Element-wise Operations with Two Arrays

In [59]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
result_addition = arr1 + arr2  # Element-wise addition
result_multiplication = arr1 / arr2  # Element-wise division

In [58]:
result_addition

array([4., 4., 4., 4.])

In [60]:
result_multiplication

array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

# Comparison Operations


In [61]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]

In [62]:
greater_than_2

array([False, False,  True,  True])